---
title: "Coverage-shared state"
author: "Luca A. Naudszus"
date: "2025-03-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
library(emmeans)
library(lme4)
library(MASS)
library(tidyverse)
library(viridis)


theme_set(theme_light()+
            theme(
              plot.title = element_text(size=rel(1),face="bold"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.background = element_blank(),
              axis.title = element_text(size=rel(1),face="bold"),
              axis.text = element_text(size=rel(1),colour = 'black'),
              strip.text = element_text(size=rel(1),colour = 'black', 
                                        face = "bold"),
              legend.text = element_text(size=rel(1)),
              legend.title = element_text(size=rel(1),face="bold")))


```

## Load data

```{r load_data}
# load data
fn = dir(file.path('results', 'ageDPFs'),
         pattern = paste("coverage_table_one_brain.csv", 
                         sep = "_"))[1]
coverage_table = read.csv(file.path('results', fn)) 
coverage_table$activity[coverage_table$activity == "Together_1" | coverage_table$activity == "Together_2"] = "Together"
coverage_table <- coverage_table %>%
  mutate(cluster = factor(cluster),
         group = factor(group),
         activity = factor(activity),
        dyadType = factor(case_when(dyadType == "True" ~ "Real",
                                     dyadType == "False" ~ "Pseudo"))) %>%
  mutate(id = factor(id))
str(coverage_table)
```

## Data exploration by clusters

```{r plot1, echo=FALSE}
ggplot(coverage_table, aes(x=session, y=coverage,
                           color=interaction(dyadType, group))) +
    # geom_boxplot(position=position_dodge(.9)) +
  geom_jitter(alpha = .7, shape = 21, size =.5, width = 0.1)+
  geom_smooth(method = "lm")+
    scale_color_manual(values=c("pink", "red", "lightblue", "blue")) +
  facet_grid(activity+dyadType~cluster)

ggsave("shared-state-g_byclusters.png", width = 14, height = 8, dpi = 400)

ggplot(coverage_table, aes(x=activity, y=coverage,
                           color=dyadType)) +
  geom_boxplot(position=position_dodge(.9)) +
  # geom_jitter(alpha = .7, shape = 21, size =.5, width = 0.1) +
  # scale_color_manual(values=c("red", "blue")) +
  facet_grid(cluster~group)

ggsave("shared-state-r_byclusters_wo.png", width = 18, height = 18  , dpi = 400)
```



## Fit model

```{r fit, message=FALSE}
# define model
model1a <- 'coverage ~ cluster*activity*dyadType*group'

# fit model
fit1a = glm.nb(model1a, data = coverage_table)
anova(fit1a)
summary(fit1a)
```

## Contrast analysis

```{r contrasts, message=FALSE}
# Get all estimated means in data frame
emm1a <- emmeans(fit1a, specs=~cluster*activity*dyadType*group, data=coverage_table, type="response") 
df.emm1a <- emm1a %>% as_tibble()

# Custom contrasts
patterns <- list()
groups <- levels(coverage_table$group)
dyadTypes <- levels(coverage_table$dyadType)
activities <- levels(coverage_table$activity)
clusters <- levels(coverage_table$cluster)
n_groups <- length(groups)
n_dyadTypes <- length(dyadTypes)
n_activities <- length(activities)
n_clusters <- length(clusters)
for (in_group in 1:n_groups) {
  for (in_dyadType in 1:n_dyadTypes) {
    for (in_activity in 1:n_activities) {
      for (in_cluster in 1:n_clusters) {
        pattern <- rep(0, n_groups*n_dyadTypes*n_activities*n_clusters)
        index <- (in_group - 1) * n_dyadTypes * n_activities * n_clusters + 
          (in_dyadType - 1) * n_activities * n_clusters +  
          (in_activity - 1) * n_clusters + in_cluster
        pattern[index] <- 1
        patterns[[paste0("c-", clusters[in_cluster], "_task-", 
                         activities[in_activity], "_d-", 
                         dyadTypes[in_dyadType], "_g-", 
                         groups[in_group])]] <- pattern
      }
    }
  }
}
# Contrasting pseudo vs. real
contrast(emm1a, method = list("C1_1 Alone Intergen" = patterns$`c-1_1_task-Alone_d-Pseudo_g-Intergen` - patterns$`c-1_1_task-Alone_d-Real_g-Intergen`,
                              "C1_1 Alone Same gen" = patterns$`c-1_1_task-Alone_d-Pseudo_g-Same gen` - patterns$`c-1_1_task-Alone_d-Real_g-Same gen`,
                              "C1_1 Together Intergen" = patterns$`c-1_1_task-Together_d-Pseudo_g-Intergen` - patterns$`c-1_1_task-Together_d-Real_g-Intergen`,
                              "C1_1 Together Same gen" = patterns$`c-1_1_task-Together_d-Pseudo_g-Same gen` - patterns$`c-1_1_task-Together_d-Real_g-Same gen`,

                              "C1_2 Alone Intergen" = patterns$`c-1_2_task-Alone_d-Pseudo_g-Intergen` - patterns$`c-1_2_task-Alone_d-Real_g-Intergen`,
                              "C1_2 Alone Same gen" = patterns$`c-1_2_task-Alone_d-Pseudo_g-Same gen` - patterns$`c-1_2_task-Alone_d-Real_g-Same gen`,
                              "C1_2 Together Intergen" = patterns$`c-1_2_task-Together_d-Pseudo_g-Intergen` - patterns$`c-1_2_task-Together_d-Real_g-Intergen`,
                              "C1_2 Together Same gen" = patterns$`c-1_2_task-Together_d-Pseudo_g-Same gen` - patterns$`c-1_2_task-Together_d-Real_g-Same gen`,

                              "C1_3 Alone Intergen" = patterns$`c-1_3_task-Alone_d-Pseudo_g-Intergen` - patterns$`c-1_3_task-Alone_d-Real_g-Intergen`,
                              "C1_3 Alone Same gen" = patterns$`c-1_3_task-Alone_d-Pseudo_g-Same gen` - patterns$`c-1_3_task-Alone_d-Real_g-Same gen`,
                              "C1_3 Together Intergen" = patterns$`c-1_3_task-Together_d-Pseudo_g-Intergen` - patterns$`c-1_3_task-Together_d-Real_g-Intergen`,
                              "C1_3 Together Same gen" = patterns$`c-1_3_task-Together_d-Pseudo_g-Same gen` - patterns$`c-1_3_task-Together_d-Real_g-Same gen`,

                              "C2_1 Alone Intergen" = patterns$`c-2_1_task-Alone_d-Pseudo_g-Intergen` - patterns$`c-2_1_task-Alone_d-Real_g-Intergen`,
                              "C2_1 Alone Same gen" = patterns$`c-2_1_task-Alone_d-Pseudo_g-Same gen` - patterns$`c-2_1_task-Alone_d-Real_g-Same gen`,
                              "C2_1 Together Intergen" = patterns$`c-2_1_task-Together_d-Pseudo_g-Intergen` - patterns$`c-2_1_task-Together_d-Real_g-Intergen`,
                              "C2_1 Together Same gen" = patterns$`c-2_1_task-Together_d-Pseudo_g-Same gen` - patterns$`c-2_1_task-Together_d-Real_g-Same gen`,

                              "C2_2 Alone Intergen" = patterns$`c-2_2_task-Alone_d-Pseudo_g-Intergen` - patterns$`c-2_2_task-Alone_d-Real_g-Intergen`,
                              "C2_2 Alone Same gen" = patterns$`c-2_2_task-Alone_d-Pseudo_g-Same gen` - patterns$`c-2_2_task-Alone_d-Real_g-Same gen`,
                              "C2_2 Together Intergen" = patterns$`c-2_2_task-Together_d-Pseudo_g-Intergen` - patterns$`c-2_2_task-Together_d-Real_g-Intergen`,
                              "C2_2 Together Same gen" = patterns$`c-2_2_task-Together_d-Pseudo_g-Same gen` - patterns$`c-2_2_task-Together_d-Real_g-Same gen`,

                              "C2_3 Alone Intergen" = patterns$`c-2_3_task-Alone_d-Pseudo_g-Intergen` - patterns$`c-2_3_task-Alone_d-Real_g-Intergen`,
                              "C2_3 Alone Same gen" = patterns$`c-2_3_task-Alone_d-Pseudo_g-Same gen` - patterns$`c-2_3_task-Alone_d-Real_g-Same gen`,
                              "C2_3 Together Intergen" = patterns$`c-2_3_task-Together_d-Pseudo_g-Intergen` - patterns$`c-2_3_task-Together_d-Real_g-Intergen`,
                              "C2_3 Together Same gen" = patterns$`c-2_3_task-Together_d-Pseudo_g-Same gen` - patterns$`c-2_3_task-Together_d-Real_g-Same gen`,

                              "C3_1 Alone Intergen" = patterns$`c-3_1_task-Alone_d-Pseudo_g-Intergen` - patterns$`c-3_1_task-Alone_d-Real_g-Intergen`,
                              "C3_1 Alone Same gen" = patterns$`c-3_1_task-Alone_d-Pseudo_g-Same gen` - patterns$`c-3_1_task-Alone_d-Real_g-Same gen`,
                              "C3_1 Together Intergen" = patterns$`c-3_1_task-Together_d-Pseudo_g-Intergen` - patterns$`c-3_1_task-Together_d-Real_g-Intergen`,
                              "C3_1 Together Same gen" = patterns$`c-3_1_task-Together_d-Pseudo_g-Same gen` - patterns$`c-3_1_task-Together_d-Real_g-Same gen`,

                              "C3_2 Alone Intergen" = patterns$`c-3_2_task-Alone_d-Pseudo_g-Intergen` - patterns$`c-3_2_task-Alone_d-Real_g-Intergen`,
                              "C3_2 Alone Same gen" = patterns$`c-3_2_task-Alone_d-Pseudo_g-Same gen` - patterns$`c-3_2_task-Alone_d-Real_g-Same gen`,
                              "C3_2 Together Intergen" = patterns$`c-3_2_task-Together_d-Pseudo_g-Intergen` - patterns$`c-3_2_task-Together_d-Real_g-Intergen`,
                              "C3_2 Together Same gen" = patterns$`c-3_2_task-Together_d-Pseudo_g-Same gen` - patterns$`c-3_2_task-Together_d-Real_g-Same gen`,

                              "C3_3 Alone Intergen" = patterns$`c-3_3_task-Alone_d-Pseudo_g-Intergen` - patterns$`c-3_3_task-Alone_d-Real_g-Intergen`,
                              "C3_3 Alone Same gen" = patterns$`c-3_3_task-Alone_d-Pseudo_g-Same gen` - patterns$`c-3_3_task-Alone_d-Real_g-Same gen`,
                              "C3_3 Together Intergen" = patterns$`c-3_3_task-Together_d-Pseudo_g-Intergen` - patterns$`c-3_3_task-Together_d-Real_g-Intergen`,
                              "C3_3 Together Same gen" = patterns$`c-3_3_task-Together_d-Pseudo_g-Same gen` - patterns$`c-3_3_task-Together_d-Real_g-Same gen`
                              ))
# # Contrasting together vs. alone
# contrast(emm1a, method = list("Cluster 1_1 Old" = patterns$c1_together_old - patterns$c1_alone_old, 
#                                           "Cluster 1_2 Old" = patterns$c2_together_old - patterns$c2_alone_old,
#                                           "Cluster 1_3 Old" = patterns$c3_together_old - patterns$c3_alone_old,
#                                           "Cluster 2_1 Old" = patterns$c4_together_old - patterns$c4_alone_old,
#                                           "Cluster 2_2 Old" = patterns$c5_together_old - patterns$c5_alone_old,
#                                           "Cluster 2_3 Old" = patterns$c6_together_old - patterns$c6_alone_old,
#                                           "Cluster 3_1 Old" = patterns$c7_together_old - patterns$c7_alone_old,
#                                           "Cluster 3_2 Old" = patterns$c8_together_old - patterns$c8_alone_old,
#                                           "Cluster 3_3 Old" = patterns$c9_together_old - patterns$c9_alone_old,
#                                           "Cluster 1_1 young" = patterns$c1_together_young - patterns$c1_alone_young, 
#                                           "Cluster 1_2 young" = patterns$c2_together_young - patterns$c2_alone_young,
#                                           "Cluster 1_3 young" = patterns$c3_together_young - patterns$c3_alone_young,
#                                           "Cluster 2_1 young" = patterns$c4_together_young - patterns$c4_alone_young,
#                                           "Cluster 2_2 young" = patterns$c5_together_young - patterns$c5_alone_young,
#                                           "Cluster 2_3 young" = patterns$c6_together_young - patterns$c6_alone_young,
#                                           "Cluster 3_1 young" = patterns$c7_together_young - patterns$c7_alone_young,
#                                           "Cluster 3_2 young" = patterns$c8_together_young - patterns$c8_alone_young,
#                               "Cluster 3_3 young" = patterns$c9_together_young - patterns$c9_alone_young
# ))

# # Contrasting old vs. young
# contrast(emm1a, method = list("Cluster 1_1 Together" = patterns$c1_together_old - patterns$c1_together_young, 
#                               "Cluster 1_2 Together" = patterns$c2_together_old - patterns$c2_together_young, 
#                               "Cluster 1_3 Together" = patterns$c3_together_old - patterns$c3_together_young, 
#                               "Cluster 2_1 Together" = patterns$c4_together_old - patterns$c4_together_young,
#                               "Cluster 2_2 Together" = patterns$c5_together_old - patterns$c5_together_young, 
#                               "Cluster 2_3 Together" = patterns$c6_together_old - patterns$c6_together_young, 
#                               "Cluster 3_1 Together" = patterns$c7_together_old - patterns$c7_together_young, 
#                               "Cluster 3_2 Together" = patterns$c8_together_old - patterns$c8_together_young,
#                               "Cluster 3_3 Together" = patterns$c9_together_old - patterns$c9_together_young, 
#                               "Cluster 1_1 Alone" = patterns$c1_alone_old - patterns$c1_alone_young, 
#                               "Cluster 1_2 Alone" = patterns$c2_alone_old - patterns$c2_alone_young, 
#                               "Cluster 1_3 Alone" = patterns$c3_alone_old - patterns$c3_alone_young, 
#                               "Cluster 2_1 Alone" = patterns$c4_alone_old - patterns$c4_alone_young,
#                               "Cluster 2_2 Alone" = patterns$c5_alone_old - patterns$c5_alone_young, 
#                               "Cluster 2_3 Alone" = patterns$c6_alone_old - patterns$c6_alone_young, 
#                               "Cluster 3_1 Alone" = patterns$c7_alone_old - patterns$c7_alone_young, 
#                               "Cluster 3_2 Alone" = patterns$c8_alone_old - patterns$c8_alone_young,
#                               "Cluster 3_3 Alone" = patterns$c9_alone_old - patterns$c9_alone_young
# ))

# Plot heat map
breaks = c((min(df.emm1a$response) + 0.001), (max(df.emm1a$response)-0.001))
ggplot(df.emm1a, aes(x=cluster, y=activity, fill=response)) + 
  geom_tile() + 
  scale_fill_viridis(option="magma", breaks=breaks, labels=c("lower", "higher")) + 
  facet_grid(dyadType~group)
```